#################################################
# Reusable workflow call to perform deploymnet  #
#################################################
name: Deploy workflow

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      release_version:
        required: true
        type: string
      deployment_group:
        required: true
        type: string
      apps:
          required: true
          type: string

jobs:
  deploy:
    name: Deploy backend services (${{ inputs.workspace }}:${{ inputs.release_version }})
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: test
      run: |
        echo "xxxxxxxxx"
        echo ${{ inputs.apps }}
        pwd
        ls -la
        ls -la .ci


    - name: Deploy to ${{ inputs.workspace }}
      run: .ci/deploy.sh empty_version ${{ inputs.workspace }} ${{ inputs.deployment_group }} ${{ join(fromJson(inputs.apps), ' ') }}