#################################################
# Reusable workflow call to perform deploymnet  #
#################################################
name: Deploy workflow

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      release_version:
        required: true
        type: string
      deployment_group:
        required: true
        type: string
      apps:
          required: true
          type: string

jobs:
  deploy:
    name: Deploy backend services (${{ inputs.workspace }}:${{ inputs.release_version }})
    runs-on: ubuntu-latest
    
    steps:
    - name: Create an aws profile
      run: |
        echo "xxxxxxxxx"
        echo ${{ inputs.apps }}

    - name: Deploy to ${{ inputs.workspace }}
      run: .ci/deploy.sh ${{ inputs.release_version }} ${{ inputs.workspace }} ${{ inputs.deployment_group }} ${{ inputs.apps }}