name: Build and push release targets
on:
  push:
    tags:
      - yongkan-dev-backend\|analyticsdash-v*

jobs:
  set_version:
    name: Extract and set version
    runs-on: ubuntu-latest
    outputs:
      release_version: "${{ steps.set_release_version.outputs.version }}"
      service_group: "${{ steps.set_release_version.outputs.service_group }}"
      tag: "${{ steps.set_release_version.outputs.tag }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set release env
        id: set_release_version
        run: |
          set -eo pipefail
          
          echo "::group::Output tag"
          tag="${GITHUB_REF#refs/*/}"
          echo "tag: ${tag}"
          echo "::set-output name=tag::$tag"
          echo "::endgroup::"
          
          echo "::group::Trying to extract version from tag '${tag}'"
          service_group="$(echo ${tag} | sed -n "s/^.*-\w*-\(\w*\)-v.*$/\1/p")"
          echo "extracted service_group: ${service_group}"
          extracted_version="$(echo ${tag} | grep --perl-regexp '(v\d+\.\d+\.\d+.*)' -o)"
          echo "extracted version: ${extracted_version}"
          echo "::endgroup::"
          
          echo "::group::Parse git hash"
          git_hash="$(git rev-parse --short HEAD)"
          echo "git hash: ${git_hash}"
          echo "::endgroup::"
          
          echo "::group::Output service group: ${service_group}"
          echo "::set-output name=service_group::$service_group"
          echo "::endgroup::"
          
          echo "::group::Output version: ${version}"
          version="${extracted_version}-${git_hash}"
          echo "version: ${version}"
          echo "::set-output name=version::$version"
          echo "::endgroup::"
